M48
; DRILL file {KiCad 9.0.4-9.0.4-0~ubuntu24.04.1} date 2025-09-24T17:28:56+0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-09-24T17:28:56+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4-9.0.4-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.100
%
G90
G05
T1
X78.591Y-64.34
X111.091Y-64.84
X143.591Y-64.34
M30
