M48
; DRILL file {KiCad 9.0.5-9.0.5~ubuntu24.04.1} date 2025-11-05T16:31:49+0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-05T16:31:49+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5-9.0.5~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.500
%
G90
G05
T1
X121.5Y-89.36
X160.46Y-68.34
M30
